#!/usr/bin/env python3
"""
Supplementary Figure 6: D-vs-J Discrimination Power Analysis
==============================================================

3-panel figure:
  (a) Discrimination power between adjacent regime pairs, 3-axis
  (b) Discrimination power, 4-axis
  (c) MDE curve vs sample size, with observed ELSA slope marked

Imports simulation infrastructure from run_dj_validation.py.

Outputs:
    outputs/figure_dj_power.pdf / .png

Usage:
    python scripts/run_dj_power.py

Note: This figure is also generated by run_dj_validation.py.  This
standalone script provides additional panel (c) MDE-vs-N analysis.
"""

import os
import sys
import time

import numpy as np
from scipy import stats
from scipy.linalg import solve_continuous_lyapunov
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

# Add project root to path
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, 'src'))
sys.path.insert(0, os.path.join(ROOT, 'scripts'))

OUTPUT_DIR = os.path.join(ROOT, 'outputs')
os.makedirs(OUTPUT_DIR, exist_ok=True)

from run_dj_validation import (
    build_A_dj_ratio,
    compute_VCP,
    compute_P_across_strata,
    apply_survivorship,
    apply_medication_compression,
    get_reference_alpha_trajectory,
    compute_discrimination_power,
    AGE_MIDS,
    AGE_LABELS,
    DJ_RATIOS,
    DJ_RATIO_NAMES,
    DJ_RATIO_VALUES,
    REGIME_COLORS,
    CONFOUND_CONDITIONS,
    CONFOUND_COLORS,
    IDX_3_IN_4,
    MED_FRACTION_BY_AGE,
    MED_COMPRESSION,
    N_RUNS,
)

from hdr_sim.dynamics import build_A, spectral_abscissa
from hdr_sim.plotting import setup_style, add_panel_label, save_figure

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
BASE_SEED = 42
N_SAMPLES_DEFAULT = 5000

# Sample sizes for MDE curve
MDE_SAMPLE_SIZES = [500, 1000, 2000, 3000, 5000, 7500, 10000]
MDE_N_RUNS = 200

# Observed ELSA values
ELSA_P_SLOPE = 0.0014
MDE_3AXIS_REPORTED = 0.0004


# ---------------------------------------------------------------------------
# Run simulation at a given N for MDE computation
# ---------------------------------------------------------------------------

def run_grid_at_N(n_samples, n_axes, ref_alphas, regime='50D/50J',
                  confound='Both', n_runs=MDE_N_RUNS):
    """Run MC simulation at a specific sample size, return P-slope distribution."""
    d_fraction = DJ_RATIOS[regime]
    Q = np.eye(n_axes)
    all_P_slopes = []

    for run_idx in range(n_runs):
        seed = BASE_SEED + run_idx * 1000 + n_samples
        rng = np.random.default_rng(seed)
        np.random.seed(seed)

        Vs, Cs = [], []
        for age_mid in AGE_MIDS:
            alpha_target = ref_alphas[age_mid]
            A, alpha_actual = build_A_dj_ratio(age_mid, d_fraction, alpha_target, n_axes)

            if alpha_actual >= 0:
                Vs.append(np.nan); Cs.append(np.nan)
                continue

            Gamma = solve_continuous_lyapunov(A, -Q)
            eigvals = np.linalg.eigvalsh(Gamma)
            if np.min(eigvals) <= 0:
                Vs.append(np.nan); Cs.append(np.nan)
                continue

            X = rng.multivariate_normal(np.zeros(n_axes), Gamma, size=n_samples)

            if confound in ('Survivorship', 'Both'):
                X = apply_survivorship(X, age_mid)
            if confound in ('Medication', 'Both'):
                X = apply_medication_compression(X, age_mid, n_axes)

            V, C = compute_VCP(X)
            Vs.append(V if V is not None else np.nan)
            Cs.append(C if C is not None else np.nan)

        Vs = np.array(Vs)
        Cs = np.array(Cs)
        V_norms, C_norms, Ps = compute_P_across_strata(Vs, Cs)

        valid = np.isfinite(Ps)
        if np.sum(valid) >= 3:
            slope = stats.linregress(AGE_MIDS[valid], Ps[valid]).slope
            all_P_slopes.append(slope)
        else:
            all_P_slopes.append(np.nan)

    return np.array(all_P_slopes)


def compute_mde_at_N(slopes):
    """Compute MDE at 80% power from a distribution of slopes."""
    valid = slopes[np.isfinite(slopes)]
    if len(valid) < 10:
        return np.nan
    sd = np.std(valid)
    n = len(valid)
    z_alpha = 1.96
    z_beta = 0.842
    return (z_alpha + z_beta) * sd / np.sqrt(n)


# ---------------------------------------------------------------------------
# Full power analysis
# ---------------------------------------------------------------------------

def run_full_power_analysis(ref_alphas):
    """
    Run the full grid for 3-axis and 4-axis, compute discrimination power,
    and compute MDE curve.
    """
    from run_dj_validation import run_full_grid

    print("\n--- Phase 1: 3-axis simulation grid ---")
    results_3 = run_full_grid(n_axes=3, ref_alphas=ref_alphas)

    print("\n--- Phase 2: 4-axis simulation grid ---")
    results_4 = run_full_grid(n_axes=4, ref_alphas=ref_alphas)

    print("\n--- Phase 3: Discrimination power ---")
    power_3 = compute_discrimination_power(results_3)
    power_4 = compute_discrimination_power(results_4)

    print("\n--- Phase 4: MDE vs sample size ---")
    mde_curve = {}
    for n_samples in MDE_SAMPLE_SIZES:
        print(f"  N={n_samples} ...")
        slopes = run_grid_at_N(n_samples, n_axes=3, ref_alphas=ref_alphas)
        mde_curve[n_samples] = compute_mde_at_N(slopes)
        print(f"    MDE = {mde_curve[n_samples]:.6f}/yr")

    return results_3, results_4, power_3, power_4, mde_curve


# ---------------------------------------------------------------------------
# Plotting
# ---------------------------------------------------------------------------

def plot_power_figure(power_3, power_4, results_3, mde_curve):
    """3-panel power analysis figure."""
    setup_style()
    fig, axes = plt.subplots(1, 3, figsize=(15, 5))

    regime_pairs = [f'{r1} vs {r2}'
                    for r1, r2 in zip(DJ_RATIO_NAMES[:-1], DJ_RATIO_NAMES[1:])]

    # --- Panel (a): Discrimination power, 3-axis ---
    ax = axes[0]
    x = np.arange(len(regime_pairs))
    bar_width = 0.18
    for i, confound in enumerate(CONFOUND_CONDITIONS):
        powers = [power_3[confound][pair]['power'] for pair in regime_pairs]
        ax.bar(x + i * bar_width, powers, bar_width,
               color=CONFOUND_COLORS[confound], label=confound, alpha=0.85)
    ax.set_xticks(x + 1.5 * bar_width)
    ax.set_xticklabels(regime_pairs, fontsize=7, rotation=15)
    ax.set_ylabel('Discrimination power')
    ax.set_title('3-axis')
    ax.set_ylim(0, 1.05)
    ax.axhline(0.8, color='grey', linestyle='--', linewidth=0.8, label='80% power')
    ax.legend(fontsize=6, loc='upper right')
    add_panel_label(ax, '(a)')

    # --- Panel (b): Discrimination power, 4-axis ---
    ax = axes[1]
    for i, confound in enumerate(CONFOUND_CONDITIONS):
        powers = [power_4[confound][pair]['power'] for pair in regime_pairs]
        ax.bar(x + i * bar_width, powers, bar_width,
               color=CONFOUND_COLORS[confound], label=confound, alpha=0.85)
    ax.set_xticks(x + 1.5 * bar_width)
    ax.set_xticklabels(regime_pairs, fontsize=7, rotation=15)
    ax.set_ylabel('Discrimination power')
    ax.set_title('4-axis')
    ax.set_ylim(0, 1.05)
    ax.axhline(0.8, color='grey', linestyle='--', linewidth=0.8, label='80% power')
    ax.legend(fontsize=6, loc='upper right')
    add_panel_label(ax, '(b)')

    # --- Panel (c): MDE curve ---
    ax = axes[2]
    ns = sorted(mde_curve.keys())
    mdes = [mde_curve[n] for n in ns]

    ax.plot(ns, mdes, 'o-', color='#8e44ad', linewidth=2, markersize=6,
            label='MDE (80% power)')

    # Mark ELSA observed slope
    ax.axhline(ELSA_P_SLOPE, color='#e74c3c', linewidth=1.5, linestyle='--',
               label=f'ELSA observed: {ELSA_P_SLOPE:.4f}/yr')

    # Mark reported 3-axis MDE
    ax.axhline(MDE_3AXIS_REPORTED, color='#27ae60', linewidth=1.5, linestyle=':',
               label=f'3-axis MDE: {MDE_3AXIS_REPORTED:.4f}/yr')

    ax.set_xlabel('Sample size per stratum')
    ax.set_ylabel('Min detectable P-slope (per year)')
    ax.set_title('MDE vs sample size')
    ax.legend(fontsize=7)
    ax.set_ylim(bottom=0)
    add_panel_label(ax, '(c)')

    fig.tight_layout()
    save_figure(fig, 'figure_dj_power', OUTPUT_DIR)
    plt.close(fig)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    print("=" * 70)
    print("Supplementary Figure 6: D-vs-J Power Analysis")
    print("=" * 70)

    t0 = time.time()

    ref_alphas = get_reference_alpha_trajectory()
    print("\nReference alpha trajectory:")
    for age_mid in AGE_MIDS:
        print(f"  age {age_mid:.0f}: alpha = {ref_alphas[age_mid]:.4f}")

    results_3, results_4, power_3, power_4, mde_curve = run_full_power_analysis(ref_alphas)

    plot_power_figure(power_3, power_4, results_3, mde_curve)

    elapsed = time.time() - t0
    print(f"\nCompleted in {elapsed:.1f}s")
    print("Done.")


if __name__ == '__main__':
    main()
